spring.application.name=firewall-alerta
server.port=8082

spring.jpa.open-in-view=false
spring.h2.console.enabled=false

reports.service.url=${REPORTS_SERVICE_URL:http://ms-reportes:8081/api/reportes/enviar}
alerts.sync.reporte.rut=${ALERTS_SYNC_RUT:00000000-0}

eureka.client.service-url.defaultZone=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://eureka:${EUREKA_PORT:8762}/eureka/}
