spring.application.name=ms-usuarios
server.port=8084

spring.jpa.properties.hibernate.format_sql=true

spring.cloud.client.discovery.enabled=true
eureka.client.service-url.defaultZone=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://eureka:${EUREKA_PORT:8762}/eureka/}
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME:}
spring.mail.password=${MAIL_APP_PASSWORD:}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.default-encoding=UTF-8
